### ISSUE TITLE
about  setup pack method

### ISSUE THREAD

**Issue by cybors** [SanForgeStudio/LuaNodeEditor#29]
### What happened?

This is really an amazing project. I would like to know what tool you used to make the installer and what tool you used to package the project into an exe file.

### Lua Node Editor Version

V1.0

**Comment by SanderKofficial** [comment]
Hey so, I personally use InnoSetup to make the .exe installer with some custom code.
and for the libraries you can check them all in wiki: https://github.com/SanForgeStudio/LuaNodeEditor/wiki/Libraries

**Comment by cybors** [comment]
Thank you very much for your reply. It is very helpful to me.
