### ISSUE TITLE
Startup Splash

### ISSUE THREAD

**Issue by SanderKofficial** [SanForgeStudio/LuaNodeEditor#8]
A splashscreen to promote and load the application for few seconds.

**Comment by SanderKofficial** [comment]
a startup splash like Visual Studio

**Comment by ImmersiveLegacy** [comment]
Made the Splash, it only needs some decoration cause atm its a white startup splash

**Comment by MeAlam1** [comment]
Added the Splash, it only shows a black gif for some reason but maybe you can understand why. the rest works

**Comment by MeAlam1** [comment]
Added 😄
